version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-rag-frontend:latest
    container_name: chatbot-rag-frontend
    ports:
      - "30003:30003"
    restart: unless-stopped
    networks:
      - RAG-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:30003"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  RAG-network:
    driver: bridge 