version: '3.8'

name: devoiminhdidauthe-chatbot

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: devoiminhdidauthe-chatbot-backend:latest
    container_name: devoiminhdidauthe-chatbot-backend
    ports:
      - "30002:30002"
    volumes:
      - ./back-end/.env:/app/.env
    restart: unless-stopped
    networks:
      - devoiminhdidauthe-chatbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: devoiminhdidauthe-chatbot-frontend:latest
    container_name: devoiminhdidauthe-chatbot-frontend
    ports:
      - "30003:30003"
    volumes:
      - ./front-end/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - devoiminhdidauthe-chatbot-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:30003"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  devoiminhdidauthe-chatbot-network:
    name: devoiminhdidauthe-chatbot-network 